spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rastogisiddhant23102003@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl:
            trust: smtp.gmail.com
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory
        transport:
          protocol: smtp
